// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqmsxrqybxsjsigqnimp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxbXN4cnF5YnhzanNpZ3FuaW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTgwNDIsImV4cCI6MjA2NDUzNDA0Mn0.kx6HfD0X45gNkbE6xyhdR-LIryhH_n-T3h0fBQuQXkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);